version: "3.8"
services:
  postgres:
    image: postgres:13.1-alpine
    container_name: port-list-postgres
    ports:
      - "5432:5432"
    volumes:
      - ./data/dump.sql:/data/dump.sql
      - ./data/init_db.sh:/docker-entrypoint-initdb.d/init-db.sh
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
  server:
    build:
      context: ./api
    container_name: port-list-server
    ports:
      - "5000:5000"
    environment:
      - FLASK_PORT=5000
      - FLASK_DEBUG=True
    volumes:
      - ./api:/app
    depends_on:
      - postgres
